const doctors = [
  {
    "email": "dr.john@example.com",
    "password": "hashedpassword1",
    "name": "Dr. John Doe",
    "phone": 1234567890,
    "photo": "photo1.jpg",
    "ticketPrice": 150,
    "role": "doctor",
    "specialization": "Cardiology",
    "qualifications": ["MBBS", "MD"],
    "experiences": ["5 years at ABC Hospital", "2 years in private practice"],
    "bio": "Expert in heart diseases.",
    "about": "I have a passion for helping people with heart-related issues.",
    "timeSlots": ["9:00 AM - 11:00 AM", "3:00 PM - 5:00 PM"],
    "reviews": [3, 5, 4, 5],
    "averageRating": 4.5,
    "totalRating": 25,
    "isApproved": "approved",
    "appointments": []
  },
  {
    "email": "dr.jane@example.com",
    "password": "hashedpassword2",
    "name": "Dr. Jane Smith",
    "phone": 9876543210,
    "photo": "photo2.jpg",
    "ticketPrice": 200,
    "role": "doctor",
    "specialization": "Neurology",
    "qualifications": ["MBBS", "MS"],
    "experiences": ["7 years at XYZ Hospital"],
    "bio": "Specialist in brain disorders.",
    "about": "Dedicated to improving neurological health.",
    "timeSlots": ["10:00 AM - 12:00 PM", "2:00 PM - 4:00 PM"],
    "reviews": [4, 3, 5],
    "averageRating": 4.7,
    "totalRating": 15,
    "isApproved": "approved",
    "appointments": []
  },
  {
    "email": "dr.sam@example.com",
    "password": "hashedpassword3",
    "name": "Dr. Sam Wilson",
    "phone": 1239874560,
    "photo": "photo3.jpg",
    "ticketPrice": 180,
    "role": "doctor",
    "specialization": "Dermatology",
    "qualifications": ["MBBS", "DDVL"],
    "experiences": ["3 years at DEF Clinic"],
    "bio": "Skin care expert.",
    "about": "Helping patients with various skin conditions.",
    "timeSlots": ["8:00 AM - 10:00 AM", "1:00 PM - 3:00 PM"],
    "reviews": [5, 4],
    "averageRating": 4.0,
    "totalRating": 10,
    "isApproved": "approved",
    "appointments": []
  },
  {
    "email": "dr.linda@example.com",
    "password": "hashedpassword4",
    "name": "Dr. Linda Brown",
    "phone": 7894561230,
    "photo": "photo4.jpg",
    "ticketPrice": 220,
    "role": "doctor",
    "specialization": "Pediatrics",
    "qualifications": ["MBBS", "MD"],
    "experiences": ["6 years at GHJ Hospital"],
    "bio": "Caring for children's health.",
    "about": "Focused on providing the best care for children.",
    "timeSlots": ["11:00 AM - 1:00 PM", "4:00 PM - 6:00 PM"],
    "reviews": [5, 4, 4, 5],
    "averageRating": 4.6,
    "totalRating": 20,
    "isApproved": "approved",
    "appointments": []
  },
  {
    "email": "dr.david@example.com",
    "password": "hashedpassword7",
    "name": "Dr. David Clark",
    "phone": 1597534862,
    "photo": "photo7.jpg",
    "ticketPrice": 270,
    "role": "doctor",
    "specialization": "Gastroenterology",
    "qualifications": ["MBBS", "MD Gastro"],
    "experiences": ["12 years at OPQ Hospital"],
    "bio": "Digestive system specialist.",
    "about": "Expert in treating digestive issues.",
    "timeSlots": ["9:00 AM - 11:00 AM", "2:00 PM - 4:00 PM"],
    "reviews": [5, 5, 4],
    "averageRating": 4.3,
    "totalRating": 15,
    "isApproved": "approved",
    "appointments": []
  }
]
